import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/context/ThemeContext'
import Header from '@/components/layouts/Header'
import ReactQueryClientProvider from '@/context/QueryClientContext'
import { Toaster } from '@/components/ui/sonner'
import { DataProvider } from '@/context/DataContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <ReactQueryClientProvider>
          <DataProvider>
            <ThemeProvider attribute="class" defaultTheme="system">
              {/* <Header /> */}
              {children}
            </ThemeProvider>
          </DataProvider>
        </ReactQueryClientProvider>
        <Toaster position='top-center' />
      </body>
    </html >
  )
}
